//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Tab
    {
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string Job_Title { get; set; }
        public int Job_Vacancy { get; set; }
        public string Job_Description { get; set; }
        public string Job_Salary { get; set; }
        public System.DateTime Job_Posted { get; set; }
        public string Job_Website { get; set; }
        public string Job_Type { get; set; }
        public string Job_Status { get; set; }
    }
}
